FROM nginx:alpine
LABEL author="René Winkler"
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

# IMPORTANT: execute these command from project path ('xxx/angular-dream-app/'). Otherwise nginx gives 'Forbidden'

# 1. You'll first need to build the project using `ng build`
# ng build --delete-output-path false

# 2. Now build the Docker image:
# docker build -t nginx-angular-dev -f Dockerfile.dev .

#3. Run the Docker container:
# docker run -p 8082:80 -v $(pwd)/dist/angular-dream-app:/usr/share/nginx/html nginx-angular-dev


